POST http://localhost:8888/sendOTP 

Content-Type: application/json
{
    "phone": "+917588664451"
}
###
POST http://localhost:8888/verifyOTP 
Content-Type: application/json

{
    "phone":"+917588664451",
    "hash":"60f2895590cc55ce240b5c200cec1cc911b790b66c456f36a5ec0df45f43ab5e.1602523199500",
    "otp":"719456"
}
###
GET https://google.com
###
POST http://localhost:5000/smstest 

Content-Type: application/json
{
    "phone": "+917588664451"
}
###

POST   http://localhost:5000/profile 

Content-Type: application/json
{
    "name": "rahul ahire"
}